spring.application.name=Backend
server.port=${PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


###Recompilar docker
###.\mvnw clean package -DskipTests
###docker build -t ufg-social-backend .
###docker stop NOMBRE_O_ID_DEL_CONTENEDOR
###docker run --env-file .env -p 8081:8081 ufg-social-backend
